//
//  EnumsUnitAI.h
//  BattleMagic
//
//  Created by madmin on 1/17/14.
//
//

#ifndef BattleMagic_EnumsUnitAI_h
#define BattleMagic_EnumsUnitAI_h

enum ArtificialIntelligenceType
{
    DEFAULT_UNIT_AI = 0,
    //mobs
    HUMAN_VILLAGER_MOB_AI,
    HUMAN_ARCHER_MOB_AI,
    HUMAN_KNIGHT_MOB_AI,
    HUMAN_MONK_MOB_AI,
    ORC_DUBOLOM_MOB_AI,
    ORC_ARCHER_MOB_AI,
    ORC_BERSERK_MOB_AI,
    ORC_SHAMAN_MOB_AI,
    SCELETON_MOB_AI,
    SCELETON_ARCHER_MOB_AI,
    SCELETON_WARRIOR_MOB_AI,
    SCELETON_LEECH_MOB_AI,
    DWARF_STONE_MOB_AI,
    DWARF_ENGINEER_MOB_AI,
    DWARF_WARRIOR_MOB_AI,
    DWARF_GEOMANT_MOB_AI,
    FROSTLING_TRAPPER_MOB_AI,
    FROSTLING_HUNTER_MOB_AI,
    FROSTLING_WARRIOR_MOB_AI,
    FROSTLING_SHAMAN_MOB_AI,
    HARRK_KILLER_MOB_AI,
    HARRK_ARCHER_MOB_AI,
    HARRK_KRUSHER_MOB_AI,
    HARRK_SHAMAN_MOB_AI,
    MEHANIC_KILLER_MOB_AI,
    MEHANIC_SHOOTER_MOB_AI,
    MEHANIC_GUARD_MOB_AI,
    MEHANIC_CONSTRUCTOR_MOB_AI,
    TROLL_TRAPPER_MOB_AI,
    TROLL_HUNTER_MOB_AI,
    TROLL_WARRIOR_MOB_AI,
    TROLL_SHAMAN_MOB_AI,
    ZOMBIE_MOB_AI,
    ZOMBIE_CROSSBOW_MOB_AI,
    ZOMBIE_DARK_KNIGHT_MOB_AI,
    ZOMBIE_SHAMAN_MOB_AI,
    ZVERG_STONE_MOB_AI,
    ZVERG_CROSSBOW_MOB_AI,
    ZVERG_WARRIOR_MOB_AI,
    ZVERG_MYSTIC_MOB_AI,
    KOBOLD_STARATEL_MOB_AI,
    KOBOLD_STONE_MOB_AI,
    KOBOLD_WARRIOR_MOB_AI,
    KOBOLD_SHAMAN_MOB_AI,
    DEMON_SMOKE_MOB_AI,
    DEMON_FIRESPITTER_MOB_AI,
    DEMON_RIG_MOB_AI,
    DEMON_SLAVEMASTER_MOB_AI,
    //summoned mobs
    SCORPION_RED_MOB_AI,
    SCORPION_BLACK_MOB_AI,
    BUG_BLACK_MOB_AI,
    BUG_GREEN_MOB_AI,
    //bullets
    ARROW_BULLET_AI,
    PULSAR_LIGHT_BULLET_AI,
    PULSAR_EARTH_BULLET_AI,
    PULSAR_FIRE_BULLET_AI,
    PULSAR_COLD_BULLET_AI,
    PULSAR_ELECTRIC_BULLET_AI,
    TRAP_BULLET_AI,
    SPEAR1_BULLET_AI,
    SPEAR2_BULLET_AI,
    GARPUN_BULLET_AI,
    PULSAR_SWAMP_BULLET_AI,
    BOLT_BULLET_AI,
    STONE_BULLET_AI,
    FIRE_WALL_BULLET_AI,
    BULLET_BULLET_AI,
    //spells
    WATER_ARMOR_SPELL_AI,
    WATER_NEEDLE_SPELL_AI,
    WATER_HEAL_SPELL_AI,
    WATER_RAIN_SPELL_AI,
    FIRE_SWORD_SPELL_AI,
    FIRE_WALL_SPELL_AI,
    FIRE_BALL_SPELL_AI,
    FIRE_RAIN_SPELL_AI,
    EARTH_POWER_SPELL_AI,
    EARTH_WALL_SPELL_AI,
    EARTH_SWARM_SPELL_AI,
    EARTH_HOLY_SPELL_AI,
    AIR_SPEED_SPELL_AI,
    AIR_LIGHTNING_SPELL_AI,
    AIR_TWIST_SPELL_AI,
    AIR_CHAIN_SPELL_AI
};

// spells backlight
enum cast_type
{
    TARGET = 0,
    AREA = 1,
    CHECK_POINT = 2
};


#endif
